<?php
defined('BASEPATH') OR exit('No direct script access allowed');

// user defined constants
// to use:
// include_once APPPATH.'config/userConstants.php';


// for uploading files
define ('UPLOAD_DIR', 'wwwUploads/');		// abs path /var/www/html/app/wwwUploads/
define ('SFTP_BASE_DIR', '/ftpUploads/');
define ('MARKSHEET_TEMPLATE', 'assets/doc/template.xlsx');

// SFTP config
define ('SFTP_HOST', '147.8.202.91');
define ('SFTP_USER', 'YOUR_SFTP_USER');
define ('SFTP_PSWD', 'YOUR_SFTP_PASSWORD');

// OL reply slip
// for secretary name
define ('FAC_SEC', '(Mr) Jason Yip');


// mapping for supportDoc tables -- updated for 2025
define ('FILE_FIELD_MAP', array ('fileD11a', 'fileD11b', 'fileD12', 'fileD14', 
  'fileD15', 'fileD16a', 'fileD16b', 'fileD18a', 'fileD18b', 'fileD17', 
  'fileD18c', 'fileD15k', 
  'fileD21a', 'fileD21b', 'fileD22', 'fileD24', 'fileD25', 'fileD26a', 'fileD26b', 
  'fileD28a', 'fileD28b', 'fileD27', 'fileD28c', 'fileD25k', 
  'fileD31a', 'fileD31b', 'fileD32', 'fileD34', 'fileD35', 'fileD36a', 'fileD36b', 
  'fileD38a', 'fileD38b', 'fileD37', 'fileD38c', 'fileD35k', 
  'fileT1', 'fileT2', 'fileV1', 'fileV2', 'fileV3'
));

// field for image only
define ('IMG_FIELD', array (
 'fileXX'
));

// field for pdf only - updated for 2025
define ('PDF_FIELD', array ('fileD11a', 'fileD11b', 'fileD12',
  'fileD15', 'fileD16a', 'fileD16b', 'fileD18a', 'fileD18b', 'fileD17', 
  'fileD18c', 'fileD15k', 
  'fileD21a', 'fileD21b', 'fileD22', 'fileD25', 'fileD26a', 'fileD26b', 
  'fileD28a', 'fileD28b', 'fileD27', 'fileD28c', 'fileD25k', 
  'fileD31a', 'fileD31b', 'fileD32', 'fileD35', 'fileD36a', 'fileD36b', 
  'fileD38a', 'fileD38b', 'fileD37', 'fileD38c', 'fileD35k', 
  'fileT1', 'fileT2', 'fileV1', 'fileV2', 'fileV3'
));

// field for txt only
define ('TXT_FIELD', array ('fileD14', 'fileD24', 'fileD34'));

// max up to fileP50, now set to fileP30 --- not used starting 2024
define ('MAX_filePNO', 2);

// number of institutions
define ('MAX_fileDNO', 3);


// 2D UPLOAD_ITEMS array - updated for 2025
// fieldname, title, description, accept file type, sample image file   
define ('UPLOAD_ITEMS', array (
  array('fileD11a', 
      'Academic transcript detailing the complete record of courses attended,grades, overall result, date of award and the grading system (pdf)',
      'Current students who have yet to be completed their studies should attach a copy of their most up-to-date official transcript.', 
      '.pdf',
      '',
      'Institution #1',
      'Academic transcript'),
  array('fileD11b',
      'English translation of the above transcript, if applicable (pdf)',
      'If the above transcript is not in English, a formally certified translation in English is required. The translation document must be stamped by the awarding institution.', 
      '.pdf',
      '',
      'Institution #1',
      'English translation of the transcript'),
  array('fileD12', 
      'Grading system of your institution, if it is not shown on your transcript (pdf)',
      'Please provide a classification of grades in English, stamped by the awarding institution.', 
      '.pdf',
      'assets/images/grading.png',
      'Institution #1',
      'Grading system'),
  array('fileD14',   // removed for 2026 - keep placeholder so index positions of UPLOAD_ITEMS stay unchanged
      '',
      '',
      '.txt',
      '',
      'Institution #1',
      ''),
  array('fileD15',
      'Rank Certificate issued by your institution (pdf)',
      'Please submit a Rank Certificate (排名證明) issued by the awarding institution, indicating your rank among the students of your cohort / major.',
      '.pdf',
      '',
      'Institution #1',
      'Rank certificate'),
  array('fileD16a', 
      'Graduation certificate, if applicable (pdf)',
      'A certificate confirming that you graduated on or before 31 Aug 2025 issued and certified by the awarding institution is required.', 
      '.pdf',
      'assets/images/graduationCert.jpg',
      'Institution #1',
      'Graduation certificate'),
  array('fileD16b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by the awarding institution.',
      '.pdf',
      '',
      'Institution #1',
      'English translation of graduation certificate'),
  array('fileD18a', 
      'Bachelor Degree Certificate, if applicable (pdf)',
      'A certificate issued and certified by the awarding insitution’s Registry is required as proof of your Bachelor’s degree qualification.', 
      '.pdf',
      'assets/images/degreeCert.jpg',
      'Institution #1',
      'Bachelor Degree Certificate 学士学位证书'),
  array('fileD18b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by your awarding institution.',
      '.pdf',
      '',
      'Institution #1',
      'English translation of 学士学位证书'),
  array('fileD17', 
      'Online Verification Report of Higher Education Qualification Certificate (教育部学历证书电子注册备案表) (pdf)',
      'Students holding qualifications from universities in China are required to submit this document, in both English and Chinese versions, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required.', 
      '.pdf',
      '',
      'Institution #1',
      'Online Verification Report of Higher Education Qualification Certificate'),
  array('fileD18c', 
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告) (pdf)', 
      'Students holding qualifications from universities in China  are required to submit this document, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required. If you upload this report, there is no need to upload the Bachelor Degree Certificate.', 
      '.pdf',
      '',
      'Institution #1',
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告)'),
  array('fileD15k',
      'Overseas Credential Evaluation Report (国外学历学位认证书) (pdf)',
      'Mainland students holding overseas qualifications are required to submit this document, issued by the Chinese Service Center for Scholarly Exchange (教育部留学服务中心).',
      '.pdf',
      '',
      'Institution #1',
      'Overseas Credential Evaluation Report'),
  array('fileD21a', 
      'Academic transcript detailing the complete record of courses attended,grades, overall result, date of award and the grading system (pdf)',
      'Current students who have yet to be completed their studies should attach a copy of their most up-to-date official transcript.', 
      '.pdf',
      '',
      'Institution #2',
      'Official transcript'),
  array('fileD21b',
      'English translation of the above transcript, if applicable (pdf)',
      'If the above transcript is not in English, a formally certified translation in English is required. The translation document must be stamped by the awarding institution.', 
      '.pdf',
      '',
      'Institution #2',
      'English translation of the transcript'),
  array('fileD22', 
      'Grading system of your institution, if it is not shown on your transcript (pdf)',
      'Please provide a classification of grades in English, stamped by the awarding institution.', 
      '.pdf',
      'assets/images/grading.png',
      'Institution #2',
      'Grading system'),
  array('fileD24',   // removed for 2026 - keep placeholder so index positions of UPLOAD_ITEMS stay unchanged
      '',
      '',
      '.txt',
      '',
      'Institution #2',
      ''),
  array('fileD25',
      'Rank Certificate issued by your institution (pdf)',
      'Please submit a Rank Certificate (排名證明) issued by the awarding institution, indicating your rank among the students of your cohort / major.',
      '.pdf',
      '',
      'Institution #2',
      'Rank certificate'),
  array('fileD26a', 
      'Graduation certificate, if applicable (pdf)',
      'A certificate confirming that you graduated on or before 31 Aug 2025 issued and certified by the awarding institution is required.', 
      '.pdf',
      'assets/images/graduationCert.jpg',
      'Institution #2',
      'Graduation certificate'),
  array('fileD26b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by the awarding institution.',
      '.pdf',
      '',
      'Institution #2',
      'English translation of graduation certificate'),
  array('fileD28a', 
      'Bachelor Degree Certificate, if applicable (pdf)',
      'A certificate issued and certified by the awarding insitution’s Registry is required as proof of your Bachelor’s degree qualification.', 
      '.pdf',
      'assets/images/degreeCert.jpg',
      'Institution #2',
      'Bachelor Degree Certificate 学士学位证书'),
  array('fileD28b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by your awarding institution.',
      '.pdf',
      '',
      'Institution #2',
      'English translation of 学士学位证书'),
  array('fileD27', 
      'Online Verification Report of Higher Education Qualification Certificate (教育部学历证书电子注册备案表) (pdf)',
      'Students holding qualifications from universities in China are required to submit this document, in both English and Chinese versions, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required.', 
      '.pdf',
      '',
      'Institution #2',
      'Online Verification Report of Higher Education Qualification Certificate'),
  array('fileD28c', 
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告) (pdf)', 
      'Students holding qualifications from universities in China  are required to submit this document, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required. If you upload this report, there is no need to upload the Bachelor Degree Certificate.', 
      '.pdf',
      '',
      'Institution #2',
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告)'),
  array('fileD25k',
      'Overseas Credential Evaluation Report (国外学历学位认证书) (pdf)',
      'Mainland students holding overseas qualifications are required to submit this document, issued by the Chinese Service Center for Scholarly Exchange (教育部留学服务中心).',
      '.pdf',
      '',
      'Institution #2',
      'Overseas Credential Evaluation Report'),
  array('fileD31a', 
      'Academic transcript detailing the complete record of courses attended,grades, overall result, date of award and the grading system (pdf)',
      'Current students who have yet to be completed their studies should attach a copy of their most up-to-date official transcript.', 
      '.pdf',
      '',
      'Institution #3',
      'Official transcript'),
  array('fileD31b',
      'English translation of the above transcript, if applicable (pdf)',
      'If the above transcript is not in English, a formally certified translation in English is required. The translation document must be stamped by the awarding institution.', 
      '.pdf',
      '',
      'Institution #3',
      'English translation of the transcript'),
  array('fileD32', 
      'Grading system of your institution, if it is not shown on your transcript (pdf)',
      'Please provide a classification of grades in English, stamped by the awarding institution.', 
      '.pdf',
      'assets/images/grading.png',
      'Institution #3',
      'Grading system'),
  array('fileD34',   // removed for 2026 - keep placeholder so index positions of UPLOAD_ITEMS stay unchanged
      '',
      '',
      '.txt',
      '',
      'Institution #3',
      ''),
  array('fileD35',
      'Rank Certificate issued by your institution (pdf)',
      'Please submit a Rank Certificate (排名證明) issued by the awarding institution, indicating your rank among the students of your cohort / major.',
      '.pdf',
      '',
      'Institution #3',
      'Rank certificate'),
  array('fileD36a', 
      'Graduation certificate, if applicable (pdf)',
      'A certificate confirming that you graduated on or before 31 Aug 2025 issued and certified by the awarding institution is required.', 
      '.pdf',
      'assets/images/graduationCert.jpg',
      'Institution #3',
      'Graduation certificate'),
  array('fileD36b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by the awarding institution.',
      '.pdf',
      '',
      'Institution #3',
      'English translation of graduation certificate'),
  array('fileD38a', 
      'Bachelor Degree Certificate, if applicable (pdf)',
      'A certificate issued and certified by the awarding insitution’s Registry is required as proof of your Bachelor’s degree qualification.', 
      '.pdf',
      'assets/images/degreeCert.jpg',
      'Institution #3',
      'Bachelor Degree Certificate 学士学位证书'),
  array('fileD38b',
      'English translation of the above certificate, if applicable (pdf)',
      'If the above certificate is not in English, a formally certified translation in English is required. The translation document copy must be stamped by your awarding institution.',
      '.pdf',
      '',
      'Institution #3',
      'English translation of 学士学位证书'),
  array('fileD37', 
      'Online Verification Report of Higher Education Qualification Certificate (教育部学历证书电子注册备案表) (pdf)',
      'Students holding qualifications from universities in China are required to submit this document, in both English and Chinese versions, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required.', 
      '.pdf',
      '',
      'Institution #3',
      'Online Verification Report of Higher Education Qualification Certificate'),
  array('fileD38c', 
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告) (pdf)', 
      'Students holding qualifications from universities in China  are required to submit this document, issued by CHSI (学信网). Please set the validity period of the report as 6 months or the longest available. Both English and Chinese versions of the report are required. If you upload this report, there is no need to upload the Bachelor Degree Certificate.', 
      '.pdf',
      '',
      'Institution #3',
      'Online Verification Report of Higher Education Degree Certificate (中国高等教育学位在线验证报告)'),
  array('fileD35k',
      'Overseas Credential Evaluation Report (国外学历学位认证书) (pdf)',
      'Mainland students holding overseas qualifications are required to submit this document, issued by the Chinese Service Center for Scholarly Exchange (教育部留学服务中心).',
      '.pdf',
      '',
      'Institution #3',
      'Overseas Credential Evaluation Report'),
  array('fileT1', 
      'Proof of the medium of instruction, if applicable (pdf)',
      'If the medium of instruction for your current academic programme and/or obtained qualification is English, please submit the relevant proof here.', 
      '.pdf',
      'assets/images/englishMedium.jpg',
      'English language requirement',
      'Proof of the medium of instruction'),
  array('fileT2', 
      'TOEFL / IELTS official score report, if applicable (pdf)',
      'Applicants from universities or comparable institutions outside Hong Kong, where the language of teaching and/or examination is not English, are required to upload their TOEFL (University’s TOEFL code: 9671) / IELTS official score report.', 
      '.pdf',
      '',
      'English language requirement',
      'Score report of English test ['),
  array('fileV1', 
      'Other document #1 - Identity document (pdf)',
      'An identity document, such as HKID or passport, is required for identity verification.', 
      '.pdf',
      '',
      'Other document - identity document',
      '['),
  array('fileV2', 
      'Other document #2 - Visa or entry permit, if applicable (pdf)',
      '', 
      '.pdf',
      '',
      'Other document - Visa or entry permit',
      '['),
  array('fileV3', 
      'Other document #3 - Additional documents requested by the programme office (pdf)',
      '', 
      '.pdf',
      '',
      'Other document (optional)',
      '[')
  ));


/* not used in 2024
// 2D UPLOAD_ITEMS array 
// fieldname, title, description, accept file type, sample image file                   
define ('UPLOAD_ITEMS', array (
  array('fileC1', 
      'Official transcript with overall average result shown (pdf)',
      'an official transcript with a complete record of courses attended, examination results, overall result and date of award issued by the Registry of institution are required. For current students which have yet to be completed, applicants should attach a copy of their most up-to-date official transcript.', 
      '.pdf',
      'assets/images/transcript0.jpeg',
      'Current academic studies',
      'Official transcript'),
  array('fileC2',
      'English translation of the above transcript (pdf)',
      'If your transcript is not in English, we need a formally certified translation in English. The translation copy must be stamped by your institution. Omit this part if the above transcript is already in English OR the transcript contains English translation side-by-side.', 
      '.pdf',
      '',
      'Current academic studies',
      'English translation of the transcript'),
  array('fileC3', 
      'Grading system of your institution (pdf)',
      'We need to know how the gradings on your transcript are classified. Please prepare such a classification of grades in English, and stamped by your institution.', 
      '.pdf',
      'assets/images/grading.png',
      'Current academic studies',
      'Grading system'),
  array('fileC4',
      'Enrollment certificate (pdf)',
      'We need a proof of your current enrollment in the institution you are currently studying.', 
      '.pdf',
      'assets/images/enrollmentCert.jpg',
      'Current academic studies',
      'Enrollment certificate'),
  array('fileC5', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      'If your transcript does not indicate an overall mark / CGPA, please prepare this. Go to Fill mark sheet session on the left panel, follow the instructions to enter the mark / GPA for all courses you have taken in your institution, a file will be generated, please upload that file.', 
      '.txt',
      '',
      'Current academic studies',
      'Mark sheet'),
  array('fileC6', 
      '',
      '', 
      '',
      '',
      '',
      ''),
  array('fileP10', 
      'Official transcript with overall average result shown (pdf only)', 
      'We need your latest transcript issued by your institution. On that transcript, we will be looking for a number which represents your overall mark / gpa.', 
      '.pdf',
      'assets/images/transcript0.jpeg',
      'Qualification obtained #1',
      'Official transcript'),
  array('fileP11',
      'English translation of the above transcript (pdf only)',
      'If your transcript is not in English, we need a formally certified translation in English. The translation copy must be stamped by your institution. Omit this part if the above transcript is already in English OR the transcript contains English translation side-by-side.', 
      '.pdf',
      '',
      'Qualification obtained #1',
      'English translation of the transcript'),
  array('fileP12', 
      'Grading system of your institution (pdf)',
      'We need to know how the gradings on your transcript are classified. Please prepare such a classification of grades in English, and stamped by your institution.', 
      '.pdf',
      'assets/images/grading.png',
      'Qualification obtained #1',
      'Grading system'),
  array('fileP13',
      '',
      '',
      '',
      '',
      '',
      ''),
  array('fileP14', 
      'Graduation certificate (pdf)',
      'We need a certificate to show that you have graduated on or before 31 Aug 2023.', 
      '.pdf',
      'assets/images/graduationCert.jpg',
      'Qualification obtained #1',
      'Graduation certificate'),
  array('fileP15',
      'English translation of the above certificate (pdf)',
      'Omit this part if the above certificate is already in English OR the document contains English translation side-by-side.',
      '.pdf',
      '',
      'Qualification obtained #1',
      'English translation of graduation certificate'),
  array('fileP16', 
      '学士学位证书: applicable to applicant from Mainland institutions only. (pdf)',
      'We need a certificate to show that you have obtained the qualification of Bachelor degree.', 
      '.pdf',
      'assets/images/degreeCert.jpg',
      'Qualification obtained #1',
      '学士学位证书'),
  array('fileP17',
      'English translation of the above certificate (pdf)',
      'Omit this part if the above certificate is already in English OR the document contains English translation side-by-side.',
      '.pdf',
      '',
      'Qualification obtained #1',
      'English translation of 学士学位证书'),
  array('fileP18', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      'If your transcript does not indicate an overall mark / CGPA, please prepare this. Go to Fill mark sheet session on the left panel, follow the instructions to enter the mark / GPA for all courses you have taken in your institution, a file will be generated, please upload that file.', 
      '.txt',
      '',
      'Qualification obtained #1',
      'Mark sheet'),
  array('fileP19',
      'Average mark for all courses you have taken in your institution (pdf)',
      'This is equivalent to the mark sheet mentioned above. A formal letter issued by your institution showing your overall average mark / CGPA in the degree you have obtained. Upload either this or the mark sheet mentioned above.',
      '.pdf',
      '',
      'Qualification obtained #1',
      'Average mark statement'),
  array('fileP20', 
      'Official transcript with overall average result shown (pdf)', 
      '', 
      '.pdf',
      '',
      'Qualification obtained #2',
      'Official transcript'),
  array('fileP21',
      'English translation of the above transcript (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #2',
      'English translation of the transcript'),
  array('fileP22', 
      'Grading system of your institution (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #2',
      'Grading system'),
  array('fileP23',
      '',
      '',
      '',
      '',
      '',
      ''),
  array('fileP24', 
      'Graduation certificate (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #2',
      'Graduation certificate'),
  array('fileP25',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #2',
      'English translation of graduation certificate'),
  array('fileP26', 
      '学士学位证书: applicable to applicant from Mainland institutions only. (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #2',
      '学士学位证书'),
  array('fileP27',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #2',
      'English translation of 学士学位证书'),
  array('fileP28', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      '', 
      '.txt',
      '',
      'Qualification obtained #2',
      'Mark sheet'),
  array('fileP29',
      'Average mark for all courses you have taken in your institution (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #2',
      'Average mark statement'),
  array('fileP30', 
      'Official transcript with overall average result shown (pdf)', 
      '', 
      '.pdf',
      '',
      'Qualification obtained #3',
      'Official transcript'),
  array('fileP31',
      'English translation of the above transcript (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #3',
      'English translation of the transcript'),
  array('fileP32', 
      'Grading system of your institution (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #3',
      'Grading system'),
  array('fileP33',
      '',
      '',
      '',
      '',
      '',
      ''),
  array('fileP34', 
      'Graduation certificate (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #3',
      'Graduation certificate'),
  array('fileP35',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #3',
      'English translation of graduation certificate'),
  array('fileP36', 
      '学士学位证书: applicable to applicant from Mainland institutions only. (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #3',
      '学士学位证书'),
  array('fileP37',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #3',
      'English translation of 学士学位证书'),
  array('fileP38', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      '', 
      '.txt',
      '',
      'Qualification obtained #3',
      'Mark sheet'),
  array('fileP39',
      'Average mark for all courses you have taken in your institution (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #3',
      'Average mark statement'),
  array('fileP40', 
      'Official transcript with overall average result shown (pdf)', 
      '', 
      '.pdf',
      '',
      'Qualification obtained #4',
      'Official transcript'),
  array('fileP41',
      'English translation of the above transcript (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #4',
      'English translation of the transcript'),
  array('fileP42', 
      'Grading system of your institution (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #4',
      'Grading system'),
  array('fileP43',
      '',
      '',
      '',
      '',
      '',
      ''),
  array('fileP44', 
      'Graduation certificate (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #4',
      'Graduation certificate'),
  array('fileP45',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #4',
      'English translation of graduation certificate'),
  array('fileP46', 
      '学士学位证书: applicable to applicant from Mainland institutions only. (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #4',
      '学士学位证书'),
  array('fileP47',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #4',
      'English translation of 学士学位证书'),
  array('fileP48', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      '', 
      '.txt',
      '',
      'Qualification obtained #4',
      'Mark sheet'),
  array('fileP49',
      'Average mark for all courses you have taken in your institution (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #4',
      'Average mark statement'),
  array('fileP50', 
      'Official transcript with overall average result shown (pdf)', 
      '', 
      '.pdf',
      '',
      'Qualification obtained #5',
      'Official transcript'),
  array('fileP51',
      'English translation of the above transcript (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #5',
      'English translation of the transcript'),
  array('fileP52', 
      'Grading system of your institution (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #5',
      'Grading system'),
  array('fileP53',
      '',
      '',
      '',
      '',
      '',
      ''),
  array('fileP54', 
      'Graduation certificate (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #5',
      'Graduation certificate'),
  array('fileP55',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #5',
      'English translation of graduation certificate'),
  array('fileP56', 
      '学士学位证书: applicable to applicant from Mainland institutions only. (pdf)',
      '', 
      '.pdf',
      '',
      'Qualification obtained #5',
      '学士学位证书'),
  array('fileP57',
      'English translation of the above certificate (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #5',
      'English translation of 学士学位证书'),
  array('fileP58', 
      'Mark sheet for all courses you have taken in your institution (txt)',
      '', 
      '.txt',
      '',
      'Qualification obtained #5',
      'Mark sheet'),
  array('fileP59',
      'Average mark for all courses you have taken in your institution (pdf)',
      '',
      '.pdf',
      '',
      'Qualification obtained #5',
      'Average mark statement'),
  array('fileT1', 
      'Proof of the medium of instruction (pdf)',
      'If the medium of instruction for the programme of the current academic studies and / or qualification obtained is in English, please submit the proof here.', 
      '.pdf',
      'assets/images/englishMedium.jpg',
      'English language requirement',
      'Proof of the medium of instruction'),
  array('fileT2', 
      'Official score report of English test (jpg / jpeg / png)',
      '', 
      '.jpg,.jpeg,.png',
      '',
      'English language requirement',
      'Score report of English test ['),
  array('fileV1', 
      'Other document #1 - identity document (pdf)',
      'Submit identity document such as visa, entry permit here', 
      '.pdf',
      '',
      'Other document - identity document',
      '['),
  array('fileV2', 
      'Other document #2 (pdf)',
      'Submit programme required document here', 
      '.pdf',
      '',
      'Other document (optional)',
      '['),
  array('fileV3', 
      'Other document #3 (pdf)',
      'Submit programme required document here', 
      '.pdf',
      '',
      'Other document (optional)',
      '[')
  ));
*/

// for storing pdf files (abs path is needed)
define ('PDF_DIR', '/var/www/html/app/wwwUploads/');

// for display
define ('PARA_SPACE', '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;');
define ('PARA_SPACE_SHORT', '&nbsp;&nbsp;&nbsp;&nbsp;');
define ('PARA_SPACE_HALF', '&nbsp;&nbsp;');

// email head - do not reply
define ('EMAIL_HEAD_NOREPLY', '[THIS IS A SYSTEM GENERATED MESSAGE - PLEASE DO NOT REPLY TO THIS EMAIL]<br/><br/>');

// email head - with reply to email address
define ('EMAIL_HEAD', '[THIS IS A SYSTEM GENERATED MESSAGE]<br/><br/>');

// list of currCode for SCDS
define ('CURRCODE_SCDS_LIST', array (137, 278, 586));

// email footer - SCDS
define ('SCDS_EMAIL_FOOTER', 'School of Computing and Data Science<br/>Faculty of Engineering<br/>The University of Hong Kong<br/>Contact us: <a href="https://engg.hku.hk/About-Us/Contact-Us#TPg-Enquiries">https://engg.hku.hk/About-Us/Contact-Us#TPg-Enquiries</a><br/>HKU Engineering TPg online admission system: <a href="https://tpgadmission.engg.hku.hk">https://tpgadmission.engg.hku.hk</a>');

// email footer - other than CS
define ('EMAIL_FOOTER', 'Faculty of Engineering<br/>The University of Hong Kong<br/>Contact us: <a href="https://engg.hku.hk/About-Us/Contact-Us#TPg-Enquiries">https://engg.hku.hk/About-Us/Contact-Us#TPg-Enquiries</a><br/>HKU Engineering TPg online admission system: <a href="https://tpgadmission.engg.hku.hk">https://tpgadmission.engg.hku.hk</a>');

// from email address
define ('FROM_TPG' ,'ENGG_TPg_admission@hku.hk');

// name of from email address
define ('TPG_EXTERNAL_NAME', 'HKU Engineering TPg Admission');

?>